ARG  RUBY_VERSION=3.4
FROM ruby:${RUBY_VERSION}

RUN apt-get update && apt-get install -y git

RUN bash -lc "gem install bundler -v 2.4.20"

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN bash -lc "bundle install"

ENV TEST_DB_USERNAME postgres
